### ISSUE TITLE
FAQ: Explanation for CAUSE: 2001

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#782]
## Where to find the issue
Suggestion for additional FAQ regarding Android CAUSE: 2001 to https://www.coronawarn.app/en/faq/

## Describe the issue
https://github.com/corona-warn-app/cwa-app-android/issues/968 "Error Reason: 2001; App does not work anymore" discusses why the error can occur. The error message displayed:

"an error occurred while trying to establish a secure connection to the server" 

is helpful, but not specific enough to fix the issue.

On Samsung Galaxy A5 (2017) SM-A520F, Android 8, the issue can be reproduced:
1. Settings > Biometrics and security >Other security settings > View security certificates, SYSTEM
2. Scroll down to T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2
3. Disable the certificate using the slider
4. Open CWA
5. Three-dot overflow menu > Settings > Reset App
6. Go through onboarding sequence and ACTIVATE EXPOSURE LOGGING
7. The error message CAUSE: 2001 appears
8. Repeat the steps above and re-enable the certificate
9. Restart CWA
10. The exposure check is now successful

## Suggested change
Add an FAQ article which explains a possible reason for CAUSE: 2001 and recommends checking for the presence and active status of the security certificate T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2 on the device.

---
Internal tracking ID: [EXPOSUREAPP-2009](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2009)

**Comment by dsarkar** [comment]
Related: https://github.com/corona-warn-app/cwa-app-android/issues/968
[EXPOSUREAPP-2009](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2009)

**Comment by dsarkar** [comment]
Suggestion:

EN

CAUSE: 2001
---

Notification: "CAUSE: 2001 Something went wrong. An error occurred while trying to establish a secure connection to the server."

A possible cause of this notification is the security certificate **T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2** being deactivated on your device. 

Follow these steps in order to activate the security certificate (The exact path depends on the device.)

- Settings > Biometrics and security > Other security settings > View security certificates, SYSTEM
- Scroll down to T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2
- Enable the certificate using the slider

Should this procedure not solve this issue, please write a report here: https://github.com/corona-warn-app/cwa-app-android/issues/968

**Comment by dsarkar** [comment]
Suggestion:

DE

URSACHE: 2001 
---


Das **Sicherheitszertifikat T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2** ist möglicherweise auf Ihrem Gerät deaktiviert. Dies ist eine bekannte Ursache, um folgende Benachrichtigung auszulösen: **"URSACHE: 2001 Etwas ist schief gelaufen. An error occurred while trying to establish a secure connection to the server."**

Führen Sie die folgenden Schritte aus, um das Sicherheitszertifikat zu aktivieren (Der genaue Pfad hängt vom Gerät ab).

- Einstellungen > Biometrische Daten und Sicherheit > Andere Sicherheitseinstellungen > Sicherheitszertifikate anzeigen, SYSTEM
- Scroll down to T-Systems Enterprise Services GmbH, T-TeleSec GlobalRoot Class 2
- Enable the certificate using the slider

Sollten diese Prozedur das Problem nicht beheben, schreiben SIe bitte Ihren Bericht hier: corona-warn-app/cwa-app-android#968

**Comment by arm-star** [comment]
> 

I do NOT want to ACTIVATE EXPOSURE LOGGING and I just want to scan the QR code, I do NOT want to use any other service of Corona Warn Ap.  I face the error occurred while I try to see the status of my test. The error is :

I will be happy if anybody can help me with this issue>:

de.rki.coronawarnapp.exception.CwaWebSecurityException: An error occurred while trying to establish a secure connection to the server

de.rki.coronawarnapp.exception.CwaWebSecurityException: An error occurred while trying to establish a secure connection to the server
at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:4)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:25)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: javax.net.ssl.SSLHandshakeException: connection closed
at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:25)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:27)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:228)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:38)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:3)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:3)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:4)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:3)
... 6 more
Caused by: java.io.EOFException: connection closed
... 26 more

**Comment by MikeMcC399** [comment]
@arm-star 

Many other users are reporting the same error today and I see that you also added yourself to https://github.com/corona-warn-app/cwa-app-android/issues/968.

It looks like a server-side issue and hopefully it will be fixed quickly.
